CREATE TABLE `apn`.`audio` (
  `AudioId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NoteId` INT UNSIGNED NOT NULL,
  `AudioNo` VARCHAR(12) NULL,
  `AudioName` VARCHAR(45) NOT NULL,
  `AudioDescription` VARCHAR(45) NULL,
  `AudioPath` VARCHAR(1024) NULL,
  `AudioCoordinateLat` DOUBLE NULL,
  `AudioCoordinateLng` DOUBLE NULL,
  `AudioCoordinateAlt` DOUBLE NULL,
  `AudioDatetime` DATETIME NULL,
  `CreatedBy` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` INT NULL,
  `ModifiedAt` DATETIME NULL,
  PRIMARY KEY (`AudioId`),
  UNIQUE INDEX `AudioID_UNIQUE` (`AudioId` ASC) VISIBLE);
  
  CREATE TABLE `apn`.`image` (
  `ImageId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NoteId` INT UNSIGNED NOT NULL,
  `ImageNo` VARCHAR(12) NULL,
  `ImageName` VARCHAR(45) NOT NULL,
  `ImageDescription` VARCHAR(45) NULL,
  `ImagePath` VARCHAR(1024) NULL,
  `ImageCoordinateLat` DOUBLE NULL,
  `ImageCoordinateLng` DOUBLE NULL,
  `ImageCoordinateAlt` DOUBLE NULL,
  `ImageDatetime` DATETIME NULL,
  `CreatedBy` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` INT NULL,
  `ModifiedAt` DATETIME NULL,
  PRIMARY KEY (`ImageId`),
  UNIQUE INDEX `ImageID_UNIQUE` (`ImageId` ASC) VISIBLE);